version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  start-server:
        docker:
          - image: cypress/base:latest
        steps:
          - checkout
          - run:
              name: Install dependencies
              command: npm install
          - run:
              name: Build the app
              command: npm run build
  deploy-to-render-staging:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Deploy to Render Staging
          # TODO: What is happening in the following command?
          command: | # echoses a message indicating that the app is being deployed to Render Staging and then triggers the deplooyment using CURL
            echo "Deploying to Render Staging" 
            curl $RENDER_STAGING_DEPLOYHOOK

workflows:
  run-tests-and-deploy-to-staging:
    jobs:
      - start-server
      - cypress/run:
          name: run-component-tests
          cypress-command: npx cypress run --component
      - deploy-to-render-staging:
          # TODO: What does the requires key do?
          requires: # ensures that the deployment onlyy happens if the component tests pass
            - run-component-tests
          # TODO: What does the filters key do?
          filters: # ensures that the deployment only happens if the branch is main 
            branches:
              only: main
